basePath: /
definitions:
  model.ArticleRequest:
    properties:
      content:
        example: Goは静的型付け言語です...
        type: string
      published:
        example: true
        type: boolean
      tags:
        example: Go,プログラミング,チュートリアル
        type: string
      title:
        example: Goプログラミングの基礎
        type: string
    required:
    - title
    type: object
  model.ArticleResponse:
    properties:
      content:
        example: Goは静的型付け言語です...
        type: string
      created_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      published:
        example: true
        type: boolean
      tags:
        example: Go,プログラミング,チュートリアル
        type: string
      title:
        example: Goプログラミングの基礎
        type: string
      updated_at:
        example: "2023-01-01T00:00:00Z"
        type: string
    type: object
  model.CsrfTokenResponse:
    properties:
      csrf_token:
        example: token-string-here
        type: string
    type: object
  model.LayoutComponentResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      height:
        type: integer
      id:
        type: integer
      layout_id:
        type: integer
      name:
        type: string
      type:
        type: string
      updated_at:
        type: string
      width:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  model.LayoutRequest:
    properties:
      title:
        example: ブログのメインレイアウト
        type: string
    required:
    - title
    type: object
  model.LayoutResponse:
    properties:
      components:
        items:
          $ref: '#/definitions/model.LayoutComponentResponse'
        type: array
      created_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      title:
        example: ブログのメインレイアウト
        type: string
      updated_at:
        example: "2023-01-01T00:00:00Z"
        type: string
    type: object
  model.TaskRequest:
    properties:
      title:
        example: 買い物に行く
        maxLength: 100
        type: string
    required:
    - title
    type: object
  model.TaskResponse:
    properties:
      created_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      title:
        example: 買い物に行く
        type: string
      updated_at:
        example: "2023-01-01T00:00:00Z"
        type: string
    type: object
  model.UserLoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  model.UserResponse:
    properties:
      email:
        example: user@example.com
        type: string
      id:
        example: 1
        type: integer
    type: object
  model.UserSignupRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: ブログCMSのバックエンドAPI
  title: Blog CMS API
  version: "1.0"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: ログインユーザーのすべての記事を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ArticleResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ユーザーの記事一覧を取得
      tags:
      - articles
    post:
      consumes:
      - application/json
      description: ユーザーの新しい記事を作成する
      parameters:
      - description: 記事情報
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.ArticleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.ArticleResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 新しい記事を作成
      tags:
      - articles
  /articles/{articleId}:
    delete:
      consumes:
      - application/json
      description: 指定されたIDの記事を削除する
      parameters:
      - description: 記事ID
        in: path
        name: articleId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 記事を削除
      tags:
      - articles
    get:
      consumes:
      - application/json
      description: 指定されたIDの記事を取得する
      parameters:
      - description: 記事ID
        in: path
        name: articleId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ArticleResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 特定の記事を取得
      tags:
      - articles
    put:
      consumes:
      - application/json
      description: 指定されたIDの記事を更新する
      parameters:
      - description: 記事ID
        in: path
        name: articleId
        required: true
        type: integer
      - description: 更新する記事情報
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.ArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ArticleResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 記事を更新
      tags:
      - articles
  /csrf-token:
    get:
      consumes:
      - application/json
      description: CSRFトークンを取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CsrfTokenResponse'
      summary: CSRFトークン取得
      tags:
      - users
  /layouts:
    get:
      consumes:
      - application/json
      description: ログインユーザーのすべてのレイアウトを取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.LayoutResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ユーザーのレイアウト一覧を取得
      tags:
      - layouts
    post:
      consumes:
      - application/json
      description: ユーザーの新しいレイアウトを作成する
      parameters:
      - description: レイアウト情報
        in: body
        name: layout
        required: true
        schema:
          $ref: '#/definitions/model.LayoutRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.LayoutResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 新しいレイアウトを作成
      tags:
      - layouts
  /layouts/{layoutId}:
    delete:
      consumes:
      - application/json
      description: 指定されたIDのレイアウトを削除する
      parameters:
      - description: レイアウトID
        in: path
        name: layoutId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: レイアウトを削除
      tags:
      - layouts
    get:
      consumes:
      - application/json
      description: 指定されたIDのレイアウトを取得する
      parameters:
      - description: レイアウトID
        in: path
        name: layoutId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LayoutResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 特定のレイアウトを取得
      tags:
      - layouts
    put:
      consumes:
      - application/json
      description: 指定されたIDのレイアウトを更新する
      parameters:
      - description: レイアウトID
        in: path
        name: layoutId
        required: true
        type: integer
      - description: 更新するレイアウト情報
        in: body
        name: layout
        required: true
        schema:
          $ref: '#/definitions/model.LayoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LayoutResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: レイアウトを更新
      tags:
      - layouts
  /login:
    post:
      consumes:
      - application/json
      description: 既存ユーザーのログイン処理
      parameters:
      - description: ログイン情報
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ユーザーログイン
      tags:
      - users
  /logout:
    post:
      consumes:
      - application/json
      description: ユーザーのログアウト処理
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ユーザーログアウト
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      description: 新しいユーザーアカウントを作成する
      parameters:
      - description: ユーザー登録情報
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserSignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.UserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 新規ユーザー登録
      tags:
      - users
  /tasks:
    get:
      consumes:
      - application/json
      description: ログインユーザーのすべてのタスクを取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TaskResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ユーザーのタスク一覧を取得
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: ユーザーの新しいタスクを作成する
      parameters:
      - description: タスク情報
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.TaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.TaskResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 新しいタスクを作成
      tags:
      - tasks
  /tasks/{taskId}:
    delete:
      consumes:
      - application/json
      description: 指定されたIDのタスクを削除する
      parameters:
      - description: タスクID
        in: path
        name: taskId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: タスクを削除
      tags:
      - tasks
    get:
      consumes:
      - application/json
      description: 指定されたIDのタスクを取得する
      parameters:
      - description: タスクID
        in: path
        name: taskId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 特定のタスクを取得
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: 指定されたIDのタスクを更新する
      parameters:
      - description: タスクID
        in: path
        name: taskId
        required: true
        type: integer
      - description: 更新するタスク情報
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: タスクを更新
      tags:
      - tasks
schemes:
- http
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
